# Generated by Django 4.1.1 on 2022-09-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=20),
        ),
    ]
