# Generated by Django 4.1.1 on 2022-09-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subscription_billing_cycle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Accounts',
        ),
    ]
