# Generated by Django 4.1.1 on 2022-09-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_subscription_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
