# Generated by Django 4.1.1 on 2022-09-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_paymentgateway_paymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('mmid', models.CharField(max_length=50)),
                ('vpa', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BankAccounts',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mmid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vpa',
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='card_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='card_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='expire_on',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
