# Generated by Django 4.1.1 on 2022-09-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bankaccount_remove_account_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('expire_on', models.CharField(max_length=20)),
                ('card_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.bankaccount')),
            ],
            options={
                'db_table': 'Cards',
            },
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.card'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
