# Generated by Django 4.1.1 on 2022-09-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_card_expire_on_alter_paymentmethod_gateway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='gateway',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.bankaccount'),
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
