# Generated by Django 4.1.1 on 2022-09-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_transaction_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
