# Generated by Django 4.1.1 on 2022-09-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
